# Generated by Django 4.2.2 on 2023-07-10 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_coupon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='is_active',
            new_name='is_expired',
        ),
    ]
